### ISSUE TITLE
Af te werken voor Septemberrelease

### ISSUE THREAD

**Issue by BRUL** [Voles/website-nejd#10]
- [ ]  de bestanden van de pijltjes zijn geupload. we moeten ze nog in de code vervangen.

**Comment by BRUL** [comment]
- [ ] tekst bij projecten moet verticaal beneden komen te staan, ter hoogte van onderkant logo.

<img width="1280" alt="screen shot 2018-09-10 at 20 07 07" src="https://user-images.githubusercontent.com/97167/45315698-547a5e80-b535-11e8-8d71-634b556691dc.png">

**Comment by BRUL** [comment]
- [ ] contactpagina: geen vet, credits zoals: 
<img width="364" alt="screen shot 2018-09-10 at 20 10 38" src="https://user-images.githubusercontent.com/97167/45315812-9dcaae00-b535-11e8-902a-609b7b06643b.png">

- [ ] contactpagina: tekst centraal, links uitgelijnd. (zoals pagina informatie)
> col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4

- [ ] contactpagina: links naar facebook en instagram (icoontjes)

- [ ] Boekenkast: foto's toevoegen, tekst,...

- [ ] Still: link naar guillaume?

- [ ]

**Comment by nielsevenepoel** [comment]
- [ ] Tekst informatie aanpassen
NEJD is het ontwerpatelier met Niels Evenepoel en Jonathan Dequeker, ontstaan na een gezamenlijke opdracht tijdens de studies Interieurarchitectuur aan het Sint-Lucas in Gent. 

Het atelier heeft ervaring met het inrichten van leefruimtes, buitenruimtes, maatmeubelen, en horeca-inrichting met projecten in de renovatie- en nieuwbouw sector.
       
NEJD ontwerpt sterk doordachte omgevingen door het formuleren van een logica vanuit uitdagende contexten. Er wordt daarbij gewerkt met formele architecturale kwaliteiten als vorm, textuur, kleur en massa. De ontwerpen zetten zich vaak voort in een grondig en kritisch uitvoeringsproces.

Aarzel niet om jouw uitdaging met [NEJD](mailto:info@nejd.be) te delen.

**Comment by BRUL** [comment]
- [ ]  beelden Folie-a-deux: 1 beeld heeft geen hoge resolutie beschikbaar, 1 beeld is verkeerd gecropped.
