### ISSUE TITLE
afbeeldingen in project Folie à deux

### ISSUE THREAD

**Issue by nielsevenepoel** [Voles/website-nejd#11]
Deze 2 beelden zijn nog niet in het juiste formaat.
![41425644_281813172431522_4828158602143334400_n](https://user-images.githubusercontent.com/29047635/45317419-3f53fe80-b53a-11e8-9735-0adec2f2e4b3.png)
![41439798_1428800563889796_8106349647024357376_n](https://user-images.githubusercontent.com/29047635/45317420-3f53fe80-b53a-11e8-9829-481880ea52d2.png)

**Comment by Voles** [comment]
@nielsevenepoel zie https://github.com/Voles/website-nejd/issues/7#issuecomment-394605466
Hebben we voor deze afbeeldingen nog grotere originelen?

**Comment by Voles** [comment]
Duplicaat van #7
