### ISSUE TITLE
projectbeelden vertikaal uitlijnen

### ISSUE THREAD

**Issue by BRUL** [Voles/website-nejd#17]
Kunnen we de beelden niet alleen horizontaal, maar ook verticaal centreren ten opzichte van het venster?

**Comment by nielsevenepoel** [comment]
Als dit lukt, ook de thumbnails verticaal centreren
![nejdwebstie2](https://user-images.githubusercontent.com/29047635/45320218-5565bd00-b542-11e8-841f-452be131a3f0.jpg)
