### ISSUE TITLE
Carousel navigeren

### ISSUE THREAD

**Issue by BRUL** [Voles/website-nejd#5]
De carousel:
- [ ] klikzones: rechts (next) groter. nu is links en rechts ingesteld op (geloof ik) 20% schermbreedte. zou beter zijn dat next een groter oppervlakte heeft.
- [ ] pijltjes: niels levert nog pijltjes aan. svg?

**Comment by Voles** [comment]
@BRUL / @nielsevenepoel nog nieuws over de pijltjes?

**Comment by nielsevenepoel** [comment]
Dag Niels,


In bijlage vind je de pijl en een screenshot om te zien waar deze moet staan.

De grote en afstand zijn hierop nog niet precies, het zou goed zijn moesten deze pijltjes ergens in het raster zitten.


Grtz,


Niels


________________________________

**Comment by Voles** [comment]
@nielsevenepoel kan je de assets via GitHub uploaden?

**Comment by BRUL** [comment]
#8 toegevoegd. Staan ze in de juiste map?

**Comment by Voles** [comment]
@BRUL de pijlen zijn nu SVG's maar met als inhoud PNG.

**Comment by BRUL** [comment]
@Voles waar kunnen we dat ergens zien?

**Comment by Voles** [comment]
@BRUL  
<img width="729" alt="screen shot 2018-09-11 at 00 02 59" src="https://user-images.githubusercontent.com/1725563/45327019-2a856400-b556-11e8-8a3d-183a82f3aa00.png">

**Comment by Voles** [comment]
@BRUL voor de pijltjes heb ik de SVG-icoontjes van Font Awesome gebruikt. Zie https://fontawesome.com/icons/chevron-right?style=solid en https://fontawesome.com/icons/chevron-left?style=solid

Elk pijltje neemt nu 50% van de schermbreedte in en de cursor is nu een `pointer`.
