### ISSUE TITLE
Afbeelding scherper

### ISSUE THREAD

**Issue by BRUL** [Voles/website-nejd#7]
- [x] Logo: kunnen we hier een svg gebruiken?
[NEJD-logo-1.svg.zip](https://github.com/Voles/website-nejd/files/1968497/NEJD-logo-1.svg.zip)
- [x] Responsive beelden: http://blog.responsive.io/post/83501648124/standards-shaping-up-for-responsive-images

**Comment by Voles** [comment]
@BRUL @nielsevenepoel responsive afbeeldingen zijn toegevoegd. Zie https://chivalrous-parent.surge.sh

**Comment by BRUL** [comment]
<img width="1280" alt="screen shot 2018-05-21 at 15 57 07" src="https://user-images.githubusercontent.com/97167/40311297-ab1a15ec-5d0f-11e8-90e7-3bb9b28e4d84.png">

**Comment by Voles** [comment]
@BRUL het bronbestand (folieadeux1.jpg) is maar 1024 × 683 pixels. Als je een groter bestand aanlevert dan kan ik de responsive images hiervan opnieuw genereren en zal het probleem opgelost zijn. De rest van de afbeeldingen doen het naar mijn weten wel goed :-)

**Comment by Voles** [comment]
@nielsevenepoel zie mijn comment hierboven (https://github.com/Voles/website-nejd/issues/7#issuecomment-394605466). Heb jij grotere afbeeldingen?
